### ISSUE TITLE
Hardcoded colour values

### ISSUE THREAD

**Issue by Fraham** [rhyneav/papercss#14]
I have noticed there are a few places in the code that uses hardcoded colour values, this does make a bit harder for someone to change the colour values to match their styling.

I would suggest adding new colours for these hardcoded values.

From my quick search i have found these references to hardcoded values
- https://github.com/rhyneav/papercss/blob/d5119c94a1ecfda8f1eacaaecd7ae07e625a7d3b/src/borders.less#L58-L60
- https://github.com/rhyneav/papercss/blob/d5119c94a1ecfda8f1eacaaecd7ae07e625a7d3b/src/code.less#L8-L13
- https://github.com/rhyneav/papercss/blob/d5119c94a1ecfda8f1eacaaecd7ae07e625a7d3b/src/container.less#L40-L55
- https://github.com/rhyneav/papercss/blob/d5119c94a1ecfda8f1eacaaecd7ae07e625a7d3b/src/popovers.less#L16-L31
- https://github.com/rhyneav/papercss/blob/d5119c94a1ecfda8f1eacaaecd7ae07e625a7d3b/src/forms.less#L1-L16

**Comment by rhyneav** [comment]
Good catch, thank you! Should be an easy fix.

**Comment by TotomInc** [comment]
Let's just add more colors values, I also hard coded one on my cards because this color wasn't declared as a variable.

**Comment by rhyneav** [comment]
@TotomInc I saw you had added the muted color in #13, which is perfect. Are there any other colors you had in mind?

**Comment by TotomInc** [comment]
Actually I don't have any other colors in mind, but I think we don't need any other colors.
