### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by rhyneav** [rhyneav/papercss#15]
The `<head>` in the index.html page is very bare bones right now. No title tag, no meta tags of keywords, etc. 

Tags to help with SEO are definitely needed, but my knowledge of what's important vs what isn't is limited. Would love to have some help with this so that PaperCSS is easier to discover via search.

**Comment by TotomInc** [comment]
I'll work on this tonight, and I think I will also clean up a bit the HTML, it looks clunky as hell. :ok_hand:
