### ISSUE TITLE
Need favicon!

### ISSUE THREAD

**Issue by rhyneav** [rhyneav/papercss#2]
Oops, don't have a favicon yet.

![image](https://user-images.githubusercontent.com/13633775/32134588-e3afaa00-bbbd-11e7-822a-b2ac91ee79bb.png)

**Comment by TotomInc** [comment]
Do you have an idea for an "official" logo?

**Comment by rhyneav** [comment]
What's ironic, is that the Chrome default favicon of a blank page is pretty fitting for PaperCSS. So maybe a more cartooned version of that? I'm open for any ideas you (or anyone else!) may have.

**Comment by MunifTanjim** [comment]
What about just an "imperfect" square?

**Comment by afzalsayed96** [comment]
![favicon](https://user-images.githubusercontent.com/14029371/32991862-38fbe73c-cd69-11e7-9751-f0b6197fba7c.png)
I suggest this should be the favicon

**Comment by TotomInc** [comment]
@afzalsayed96 thanks for your submission, but I feel you should also sharp the inside-borders of the icon, it looks a bit too rough. What are your thoughts @rhyneav ?

**Comment by afzalsayed96** [comment]
@TotomInc I didn't quite get you.
Built this favicon using papercss itself.

### HTML
```
<div class="row flex-center">
      <div class="row flex-center child-borders">
          <h1>P</h1>
       </div>
</div>
```
### CSS
```
.child-borders > * {
    border: 4px solid #41403e;
}
h1 {
    font-size: 4rem;
    padding: 0% 15%;
}
```

**Comment by rhyneav** [comment]
I dig it! Favicon made by the framework, nice!

@TotomInc I see your point, but I think the favicon will be to small to really see that it's not perfectly imperfect on the inside. To that point, what browser did you use to display the icon for the screenshot @afzalsayed96?

**Comment by nafis-fuad** [comment]
@rhyneav, You are right, Chrome's default favicon is a great fit for your framework. I wondered about it too. and maybe we could replicate this same icon to display on other browsers too... What do you say? 

And I have found a solution for you. And here's a preview: 
![ms-icon-150x150](https://user-images.githubusercontent.com/24988773/33005390-cb0ea1f6-cdef-11e7-9d20-7ad7a87a916b.png)

And I would say, imperfectness won't be necessary ( just for favicon ). If you like my idea, I can complete the process for you. 

BTW, loved PaperCSS. Keep up the great work. we're happy to contribute.  

Nafis Fuad
@nafis-fuad

**Comment by afzalsayed96** [comment]
@rhyneav the previous preview was using Firefox. Here's a preview in Chrome

![favicon chrome](https://user-images.githubusercontent.com/14029371/33005579-6c41924e-cdec-11e7-88ee-0feff8ab7c18.png)

For Edge, favicon cannot be viewed in localhost but it will work perfectly on deployed webpage

**Comment by TotomInc** [comment]
@afzalsayed96 favicon looks a bit too light IMO, and the borders are not enough visible.

@nafis-fuad is it possible to add something like the  *P* with the PaperCSS font use? It will customize it a bit more, otherwise it's a nice favicon!

**Comment by nafis-fuad** [comment]
@TotomInc, Thank you for giving m favicon a thought. And yeah, I like your idea. Definitely worth a try.

**Comment by nafis-fuad** [comment]
# Maybe this one helps.
![favicon-real2](https://user-images.githubusercontent.com/24988773/33015900-a2a886c4-ce16-11e7-9a8c-b7a5eb2710d8.png)  

Had to try a lot of combinations. But this one worked for me. Hope you'll find it interesting.  

I've generated all the files required.
@nafis-fuad

**Comment by rhyneav** [comment]
@nafis-fuad could you please link a screenshot of what it would look like in a browser? Similar to what @afzalsayed96 has done.

**Comment by TotomInc** [comment]
What's the state of the favicon? Have you done a choice?

**Comment by rhyneav** [comment]
No decision yet @TotomInc. Wanted to see what @nafis-fuad's looked like in a browser first.

I personally like @afzalsayed96's a lot. I think it's neat that it was made by the framework. Plus, he already has #38 open with it.

**Comment by nafis-fuad** [comment]
Here you go, @rhyneav.

![favicon-test](https://user-images.githubusercontent.com/24988773/33051935-9ebeeeb0-ce96-11e7-8672-f33c7f4690d8.png)

@nafis-fuad

**Comment by TotomInc** [comment]
I personally prefer @afzalsayed96's favicon, your favicon @nafis-fuad is a bit messy, maybe because of the top right folding border.

**Comment by rhyneav** [comment]
Totally agree. The fold looks great in a bigger image, but gets a little distorted when in a small icon. Thank you for putting that together though, @nafis-fuad! 

I'm going to go ahead and merge in #38 with @afzalsayed96's favicon.

**Comment by nafis-fuad** [comment]
### It's Ok.  

@nafis-fuad
