### ISSUE TITLE
Update release to match documenation.

### ISSUE THREAD

**Issue by vpicone** [rhyneav/papercss#23]
The current download link (v1.0.1) doesn't include Cards, Badges etc. These classes are only accessible if the user clones and compiles the CSS themselves.

**Comment by rhyneav** [comment]
Whoops! My bad on that. 

The latest release (with all of those features) is [available for download](https://github.com/rhyneav/papercss/releases/tag/v1.1.0)

I'm still working on how to best put out releases while still keeping the documentation matching. Right now the documentation is built off of the master branch which is not ideal. I'll have to update it to keep things consistent.
