### ISSUE TITLE
npm package/registry

### ISSUE THREAD

**Issue by joelwallis** [rhyneav/papercss#24]
Hello Rhyne,

Although it's a CSS library, npm is used as default package manager for front-end related stuff. What about publishing papercss to npm? :-)

You have two options:

- **publish it as a standalone package ([the `papercss` namespace is available](https://www.npmjs.com/package/papercss))**
  - good: installing it would be just a matter of `npm i -S papercss`
  - bad: there is already a `paper-css` package, which may cause confusion to users
- **publish it in your user's space (e.g.: `@rhyneav/papercss`)**
  - good: the naming would match GitHub's URL (e.g.: `npm i -S @rhyneav/papercss`)
  - bad: longer package name

The npm documentation is quite friendly and explains really well [how to publish a package](https://docs.npmjs.com/getting-started/publishing-npm-packages). You can also add contributors to it, but I'm still not sure how this second part works (I'm new on this open source creating thing too).

**Comment by rhyneav** [comment]
Hey Joel,

Thank you for the heads up with this! I went ahead and snagged the papercss namespace and have been playing around with publishing to that. While there may be some confusion between paper-css and papercss, I think it's worth having the concise name. 

It's available now at the [papercss namespace](https://www.npmjs.com/package/papercss) you referenced above. There's still a little bit of updating to be done with this (moving normalize.css to a regular dependency, changing the .less references to that around, and adding documentation). I'm currently just basing things (as much as possible) off of how Bootstrap (v3) organizes their npm package, though it's not perfect. 

I'll post an update to this issue when the above concerns are fully resolved. Until then, `npm i -S papercss` will give you the latest (v1.1.0) css files within the /dist folder!

**Comment by joelwallis** [comment]
Awesome!

Now, I think the next step would be to create a flow to release versions. I see that you're creating [release posts on GitHub](https://github.com/rhyneav/papercss/releases/tag/v1.1.0), with additional notes about changes, etc. Do you have a marketing toolset, like a Twitter profile, etc.? It would be nice to have, but we can discuss it on a dedicated issue.

Also, document your concerns about code organization on GitHub. Contributors might even get some of them to work on. 🙂

**Comment by rhyneav** [comment]
That's a great idea, and @brodybits let me know that the Twitter handle papercss is available. I went ahead and signed up for that. I'd like to keep the release posts with changes/updates/thank yous, but a standard process needs to be put in place. Maybe weekly releases? 

You are absolutely right about documenting more of my concerns on Github. Still getting used to the whole open source thing :)

**Comment by rhyneav** [comment]
Going to go ahead and close this for now. [PaperCSS is currently on NPM](https://www.npmjs.com/package/papercss) and Gitflow is currently going to be our workflow of choice to getting releases consistent with docs (per #27)
