### ISSUE TITLE
Cooperate with paper-css?

### ISSUE THREAD

**Issue by brodybits** [rhyneav/papercss#25]
From #24 I discovered <https://github.com/cognitom/paper-css>, last updated 8-9 months ago, which *could* be handy for some developers. I wonder if we should consider some alternatives such as:
- rename this project and see how it works with paper-css
- fork paper-css as something like print-paper-css
- do nothing

**Comment by rhyneav** [comment]
Wow, paper-css is very cool! I wish I had done some more extensive Googling on the phrase "paper css".

Are you suggesting that there might be a naming conflict if a developer was using both papercss and paper-css in the same project?

**Comment by brodybits** [comment]
The other "paper-css" project looks dead (no updates since March, author not so responsive) so I wouldn't worry so much about a naming conflict. We *could* fork it as something like "print-paper-css" or "page-paper-css" (would be MIT license). Closing for now.
