### ISSUE TITLE
Keeping Docs Consistent with Features

### ISSUE THREAD

**Issue by rhyneav** [rhyneav/papercss#27]
#17 looks great and ready to merge into master, but that would update the documentation on getpapercss.com, but would the downloadable css file would not have the updates. That would need to be rebuilt and put into a release. This causes an issue of the documentation not matching the available features if downloaded.

Would it be best to keep a separate branch for what gets shown on getpapercss.com, instead of just using the master branch? That way the most up to date features are in the master, but the download/documentation match up online. Every Sunday could be a release day where the new features are built and released via Github releases, and the website is updated to match.

Does anyone have any thoughts or experience with the best workflow to follow here?

**Comment by Fraham** [comment]
I would suggest using git-flow https://datasift.github.io/gitflow/IntroducingGitFlow.html
It will allow for master to keep with the current release so that the documentation will always match.
You will then be able to set up a pipeline so when there is a new merge into master it could automatically update the website.
I wouldn't worry about having a weekly release, I think it is   better to have a release once there is a new feature  which has been tested

**Comment by rhyneav** [comment]
I really like that workflow, it makes a lot of sense. Thank you for sharing that! And that's a good point about releases. No point in trying to force things out the door every Sunday.

So moving to the GitFlow methodology:
- PaperCSS master branch is at version 1.1.0
- Create a new branch, develop, where PRs from feature branches will be merged into
- After enough new features in the develop branch, create branch v1.2.0
- Once this branch has been fully tested, merge into master

Am I missing anything?

**Comment by Fraham** [comment]
Yeah that all sounds good 👍

**Comment by rhyneav** [comment]
Awesome! Check out #30 with the updated documentation. Does this mean the existing PRs need to be rebased off of develop so that they can be merged in to that branch instead of master?

And thank you for your help with this! Really wish I knew about GitFlow months ago!

**Comment by Fraham** [comment]
Yeah that would be the best thing to do. I have changed my PR's

**Comment by rhyneav** [comment]
Perfect, thank you!
