### ISSUE TITLE
Adding modern components such as carousel, cards, modals, popovers, ...

### ISSUE THREAD

**Issue by TotomInc** [rhyneav/papercss#3]
What do you think about adding modern components (that's how I call them) in the framework? Such as popovers, carousel, cards, ...

Also, what do you plan for your framework? Something more complex and complete like Bootstrap, Semantic UI or stay simple with minimal things such as what you already implemented?

Let me know what you think about those components, I would like to implement them if you are okay.

**Comment by rhyneav** [comment]
Hey TotomInc! In terms of complexity, I'd like to keep JavaScript of the framework for now and focus on it being a simple(ish) CSS framework. It will never be as bare bones as something like http://getskeleton.com/, but PaperCSS could stand to benefit from popovers, cards, and other "modern components". 

So go for it! I'd love to see you add those.

**Comment by TotomInc** [comment]
My idea too was to keep out Javascript of the framework, I'll try to do some popovers and cards.

**Comment by rhyneav** [comment]
Sounds great, excited to see it!

**Comment by TotomInc** [comment]
It's currently looking [like that](https://i.imgur.com/HmqmOPK.gifv). Need to finish a few things and I'll send a PR if that's okay for you.

**Comment by rhyneav** [comment]
That looks awesome! Love it!

**Comment by rhyneav** [comment]
@TotomInc what are your thoughts on cards? I think that's the next low hanging fruit for modern components. Thank you again for making the popovers, they look great!

**Comment by TotomInc** [comment]
I'll see what I can do with cards. 👍

**Comment by TotomInc** [comment]
A basic card look like [this](https://i.imgur.com/jXaWjW5.png).

**Comment by Fraham** [comment]
Can this ticket be closed now?

**Comment by TotomInc** [comment]
Yes this ticket can be closed and if there are more *moderns* components to add, I'll do it as a new feature.
