### ISSUE TITLE
SSL - To enable HTTPS on website

### ISSUE THREAD

**Issue by afzalsayed96** [rhyneav/papercss#41]
I noticed that SSL is not enabled on getpaperccs.com. I've heard about Let's Encrypt that it provides HTTPS certificates for free and it is fairly simple to install and renew a certificate with them. Refer: https://letsencrypt.org/getting-started/

**Comment by rhyneav** [comment]
Thank you for the heads up! It looks like it is enabled via the Netlify dashboard. 
![image](https://user-images.githubusercontent.com/13633775/33033257-cbe87410-cdf1-11e7-9839-b8d70dec4bcd.png)

I'll reach out to their support to see why it's not showing up as fully secure.  
![image](https://user-images.githubusercontent.com/13633775/33033227-b6458a6c-cdf1-11e7-97c8-f03814ae4484.png)

**Comment by rhyneav** [comment]
I may have found the culprit...
![image](https://user-images.githubusercontent.com/13633775/33040215-5fa35b00-ce08-11e7-8a42-673d7edf9080.png)

Looks like an http image is ruining the https party!

**Comment by rhyneav** [comment]
Fixing the image fixed it, things are secure yet again!

![image](https://user-images.githubusercontent.com/13633775/33040701-e0bcb9a6-ce09-11e7-8df4-fa34dd444ddb.png)
