### ISSUE TITLE
What about Breadcrumbs?

### ISSUE THREAD

**Issue by amanbayev** [rhyneav/papercss#50]
Is there a vision on how Breadcrumbs should look using PaperCSS?
I am trying to apply this framework on a project and it needs to have some breadcrumbs to indicate users current location regarding to sitemap.
Please help or advise

**Comment by rhyneav** [comment]
That's a great question, and something I have not thought about. I like how simple [Bootstrap's breadcrumbs](https://v4-alpha.getbootstrap.com/components/breadcrumb/) are. So maybe something along those lines? However, I'm 100% open to any cool ideas with this. Breadcrumbs would be a nice feature to have!

**Comment by TotomInc** [comment]
That what I wanted to say, Bootstrap CS breadcrumbs do the job, you could easily do the same and customize it to give it a paper look.

**Comment by Kaperskyguru** [comment]
Bootstrap breadcrumbs is cool.... But we all kn we need to tweak it a little.... Let's try drawing a breadcrumb on paper and implement the design from its look..... It shouldn't look exactly like that of bootstrap..

**Comment by amanbayev** [comment]
closing this for #62
