### ISSUE TITLE
x-index overflow in mobile view

### ISSUE THREAD

**Issue by afzalsayed96** [rhyneav/papercss#52]
The x index is scroll-able in mobile view. Need to fix this!

**Comment by rhyneav** [comment]
Ah dang. The culprit is the CDN url. Just a simple `overflow-wrap: break-word;` style should fix this.

![img_5081](https://user-images.githubusercontent.com/13633775/33082758-8a7178be-ceab-11e7-997d-917a1e39183b.PNG)

**Comment by afzalsayed96** [comment]
Should I add it in the hotfix along with issue #47 ?

**Comment by TotomInc** [comment]
So shouldn't this property be added to a component?

**Comment by afzalsayed96** [comment]
We missed this... 

![image](https://user-images.githubusercontent.com/14029371/33124590-8beb4d2a-cfa3-11e7-9ae9-b0a52ecc2d89.png)

**Comment by afzalsayed96** [comment]
```
table tbody tr td {
    padding: 8px;
    line-height: 1.5;
    vertical-align: top;
    border-top: 1px dashed #d9d9d8;
}
```
The padding is the problem

**Comment by afzalsayed96** [comment]
Proposed fix: 
- Padding for ```table tbody tr td``` must be in percentage
- Adding ```!important``` in media query for container width
```.container {
    width: 100%;
    max-width: 960px;
    position: relative;
    margin: 0 auto;
    @media @medium-screen {
        width: 85% !important;
    }
    @media @xsmall-screen {
        width: 90% !important;
    }
```

**Comment by rhyneav** [comment]
Good catch with the padding! And is the `!important` tag needed here?

**Comment by TotomInc** [comment]
I think the `!important` tag override the default `width` which is set upper.

**Comment by afzalsayed96** [comment]
@rhyneav Yes it's needed

![image](https://user-images.githubusercontent.com/14029371/33132806-ac5dd876-cfc0-11e7-99cb-e31ad88890c9.png)

![important](https://user-images.githubusercontent.com/14029371/33132920-14238f5a-cfc1-11e7-9e1d-bf7e0d3f5a60.png)

@TotomInc It does override only for the specified screen-size which is actually desired to achieve

**Comment by rhyneav** [comment]
Gotcha! Could this also be solved by changing the html from 
```html
<div class="container paper">
```
to
```html
<div class="container">
  <div class="paper">
```
That way the paper width of 100% is within the container and not overriding it. 

I'm just trying to find ways around using `!important`. This way it's easier for someone using PaperCSS to override the styles if need be.

**Comment by afzalsayed96** [comment]
Great! Your fix works. I totally forgot about problem with overriding ```!important``` 😅

**Comment by afzalsayed96** [comment]
Is anyone assigned to this issue?

**Comment by rhyneav** [comment]
Nope! Do you want to take this one @afzalsayed96?

**Comment by afzalsayed96** [comment]
I'm on it

**Comment by rhyneav** [comment]
You rock, thank you @afzalsayed96!
