### ISSUE TITLE
PaperCSS just reached 1,000 stars!

### ISSUE THREAD

**Issue by TotomInc** [rhyneav/papercss#60]
Thanks to everyone who contributed on the code, gave us their idea, feedback, ...  PaperCSS is a very interesting framework, and I hope it will grow even more! There is still so much things to do to improve this framework!

**Comment by mrpinkcat** [comment]
**GG guys**

**Comment by amanbayev** [comment]
1,000 and counting :)
gg

**Comment by rhyneav** [comment]
What a wild ride, and thank you to everyone who has contributed so far! I'm excited to see how PaperCSS evolves!

**Comment by rhyneav** [comment]
Since we're now at 1,200 stars (another awesome milestone), I'm going to close this :)
