### ISSUE TITLE
Merge Issues

### ISSUE THREAD

**Issue by afzalsayed96** [rhyneav/papercss#61]
Correct me if I'm wrong
I've noticed that since we are merging PRs to 2 different branches i.e. master for hotfixes and develop for features. This will create merge issues when new features will be merged from develop branch to the master branch. Since, develop branch doesn't gets refreshed from master branch after the hotfixes.
This might be the reason which caused issue #47
IMO to tackle this all the contribution should be done to only develop branch for time being and the code must be modularised so that everyone does not end up changing the same file (index.html) at the same time.

**Comment by amanbayev** [comment]
I agree 

> IMO to tackle this all the contribution should be done to only develop branch for time being and the code must be modularised so that everyone does not end up changing the same file (index.html) at the same time

**Comment by rhyneav** [comment]
Totally understand that. What I've been doing for the time being for hotfixes is merging it into master and then merging it into develop ([as specified here](http://nvie.com/posts/a-successful-git-branching-model/)). This way the develop branch is kept consistent with master preventing merge problems down the road. This process is a little bit more manual than I'd like, but it matches with the [Gitflow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) methodology. 

Also, check out #48 in regards to modularizing :)

**Comment by afzalsayed96** [comment]
Thanks for clarification 😃

**Comment by rhyneav** [comment]
Sure thing! It's not perfect, and we're still working out the kinks in the development workflow. So I'm all ears for these types of conversations to improve things.
