### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by afzalsayed96** [rhyneav/papercss#68]
As the code and community grows it becomes more difficult to keep everything organized. According to GitHub's [Building a strong community](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) we need to setup guidelines for repository contributors.
Inspite this is briefly defined in [README](https://github.com/rhyneav/papercss/blob/master/README.md) I feel it must be separated from there due to the length of readme and contribution guidelines must be laid more specifically in another file to follow best practices.

**Comment by rhyneav** [comment]
It is merged and live! Thank you for adding this.
