### ISSUE TITLE
More explicit license statement?

### ISSUE THREAD

**Issue by brodybits** [rhyneav/papercss#9]
Thanks for the nice framework, I found it through the following Tweet: <https://twitter.com/speckyboy/status/925407518565851136>

In <package.json> the license is set to ISC which I really like (extremely simple and permissive). Is this your intention and can you make it more explicit?

**Comment by rhyneav** [comment]
Hey, I really appreciate that, thank you! 

I'm glad you brought up licensing. It was something I ran through very quickly, but you are right; it needs to be more explicit.

**Comment by joelwallis** [comment]
Indeed!

I just opened a PR that adds a `license` file and updates the `package.json` to include @rhyneav's full name. 😁
